### ISSUE TITLE
Script error when importing a specific segment (v1.99.21)

### ISSUE THREAD

**Issue by tm67602** [knot126/Smash-Hit-Blender-Tools#7]
This error only applied to one segment I imported, called "fly" from segments/river/path/. I imported about 12-15 different segments afterwards, including the fly cube segment from segments\endless\narrow\obstacles\, but none of them had an error. 

Here is the image:
https://user-images.githubusercontent.com/100551859/168566269-928a1e48-98b5-48cd-8b45-bf89c8812dd4.PNG

Here is the log entry:
Python: Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender_tools.py", line 814, in execute
    return sh_import_segment(self.filepath, context, True)
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender_tools.py", line 684, in sh_import_segment
    colour = sh_parse_colour(properties.get("color", "0.5 0.5 0.5"))
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender_tools.py", line 603, in sh_parse_colour
    return [(float(a[0]), float(a[1]), float(a[2])), (float(a[3]), float(a[4]), float(a[5])), (float(a[6]), float(a[7]), float(a[8]))]
ValueError: could not convert string to float: ''

location: <unknown location>:-1

**Comment by knot126** [comment]
I can't fix this right now, but I think if you add the line `a = removeAllEqualTo(a, "")` before the for loop it should fix it.

**Comment by knot126** [comment]
Fixed in 1.99.22
